[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"


[project]
name = "monsoon"
version = "0.0.1"
dependencies = ["click","requests", "monsoon","pandas"]

[project.scripts]
monsoon-cli = "monsoon.cli:cli"

[tool.setuptools]
packages = ["monsoon"]